[platformio]
description = SmartTrafficLight test environment
default_envs = native
src_dir = ../src
include_dir = ../include
test_dir = ../test

[env:native]
platform = native
test_framework = unity
lib_deps = fabiobatsilva/ArduinoFake@^0.4.0
build_flags = 
    -D UNITY_INCLUDE_CONFIG_H
    -D UNITY_TEST
    -I ../src
    -std=gnu++11
test_build_src = yes
lib_ldf_mode = deep+
lib_compat_mode = strict