name=SmartTrafficLight
version=1.0.0
author=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
maintainer=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
sentence=A non-blocking library for traffic lights control with optional pedestrian button.
paragraph=It allows managing traffic lights using state machine (millis()) ensuring the processer doesn't crash. It supports custom timout configurations and interruption by pedestrian button. Future features will enable smart traffic managing with sensors.
category=Device Control
url=https://github.com/vicenteraphael/SmartTrafficLight
architectures=*