name=SmartTrafficLight
version=1.0.0
author=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
maintainer=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
sentence=A non-blocking Arduino library for traffic lights control with optional pedestrian button.
paragraph=It allows managing traffic lights using a Finite State Machine, ensuring non-blocking operation. It supports custom interval configurations, along with interruption by pedestrian button. Its specific event functions enhances customization and facilitates communication between traffic lights. Future features will enable smart traffic managing with sensors.
category=Device Control
url=https://github.com/vicenteraphael/SmartTrafficLight
architectures=*