name=SmartTrafficLight
version=1.0.1
author=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
maintainer=Raphael Vicente de Oliveira <vicenteraphael@gmail.com>
sentence=A non-blocking Arduino library for managing traffic lights with optional pedestrian button.
paragraph=It allows managing traffic lights using a Finite State Machine, ensuring non-blocking operation. It supports custom interval configurations, along with interruption by pedestrian button. Its getters and control methods permit changes in state without interrupting the system behaviour. Its specific event functions enhances customization and facilitates communication between traffic lights.
category=Device Control
url=https://github.com/vicenteraphael/SmartTrafficLight
architectures=*