name: Check Arduino

on:
  push:
  pull_request:
  schedule:
    # Run every Saturday at 12 PM UTC to catch breakage caused by new rules added to Arduino Lint.
    - cron: "0 12 * * SAT"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Arduino lint
        uses: arduino/arduino-lint-action@v2
        with:
          compliance: strict
          library-manager: update
          project-type: library