name: Check Arduino

on:
  push:
  pull_request:
  schedule:
      # Run every Saturday at 12 AM UTC to catch breakage caused by new rules added to Arduino Lint.
    - cron: "0 12 * * SAT"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: arduino/arduino-lint-action@v2
        with:
          compliance: strict
          library-manager: submit
          project-type: library