name: Spell Check

on:
  push:
  pull_request:
  schedule:
    # Run every Saturday at 12 PM UTC to catch new misspelling detections resulting from dictionary updates.
    - cron: "0 12 * * SAT"
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Spell check
        uses: codespell-project/actions-codespell@master